# rubies:
#   - 3.1
#   - 3.0
#   - 2.7

# rails:
#   - actioncable
#     - integration
#   - activejob
#     - integration

version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.2.3

commands:
  run-tests:
    parameters:
      gem:
        type: string
      command:
        type: string
        default: rake test
    steps:
      - run:
          name: Run tests
          command: |
            env COMPOSE_TLS_VERSION=TLSv1_2 \
            docker-compose -f .circleci/docker-compose.yml run app runner << parameters.gem >> "<< parameters.command >>"

jobs:
  test-job:
    parameters:
      gem:
        type: string
      command:
        type: string
        default: rake test
      ruby:
        type: string
        default: ruby:latest
      mysql:
        type: string
        default: mysql:latest
      mysql_prepared_statements:
        type: boolean
        default: false
      nodes:
        type: integer
        default: 1
    machine:
      image: ubuntu-2004:202111-02
      docker_layer_caching: true
      resource_class: large
    parallelism: << parameters.nodes >>
    environment:
      RUBY_IMAGE: << parameters.ruby >>
      MYSQL_IMAGE: << parameters.mysql >>
      MYSQL_PREPARED_STATEMENTS: << parameters.mysql_prepared_statements >>
    steps:
      - checkout
      - run:
          name: Make cache directory
          command: |
            sudo mkdir /caches
            sudo chown -R $USER:$USER /caches
      - restore_cache:
          keys:
            - v1-<< parameters.ruby >>-{{ .Branch }}
          paths:
            - /caches/app.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=app --build-arg MYSQL_IMAGE=$MYSQL_IMAGE --build-arg RUBY_IMAGE=$RUBY_IMAGE -t app -f .circleci/Dockerfile .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/app.tar app
      - save_cache:
          key: v1-<< parameters.ruby >>-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/app.tar
      - run-tests:
          gem: << parameters.gem >>
          command: << parameters.command >>
      - store_test_results:
          path: test-reports

workflows:
  version: 2
  test:
    jobs:
      - test-job:
          matrix:
            parameters:
              ruby: ["ruby:2.7", "ruby:3.0", "ruby:3.1", "ruby:latest"]
          name: actioncable-<< matrix.ruby >>
          gem: actioncable
      #- actioncable-integration
      - test-job:
          matrix:
            parameters:
              ruby: ["ruby:2.7", "ruby:3.0", "ruby:3.1", "ruby:latest"]
          name: actionmailbox-<< matrix.ruby >>
          gem: actionmailbox
      - test-job:
          matrix:
            parameters:
              ruby: ["ruby:2.7", "ruby:3.0", "ruby:3.1", "ruby:latest"]
          name: actionmailer-<< matrix.ruby >>
          gem: actionmailer
      - test-job:
          matrix:
            parameters:
              ruby: ["ruby:2.7", "ruby:3.0", "ruby:3.1", "ruby:latest"]
          name: actionpack-<< matrix.ruby >>
          gem: actionpack
      - test-job:
          matrix:
            parameters:
              ruby: ["ruby:2.7", "ruby:3.0", "ruby:3.1", "ruby:latest"]
          name: actiontext-<< matrix.ruby >>
          gem: actiontext
      - test-job:
          matrix:
            parameters:
              ruby: ["ruby:2.7", "ruby:3.0", "ruby:3.1", "ruby:latest"]
          name: actionview-<< matrix.ruby >>
          gem: actionview
      - test-job:
          matrix:
            parameters:
              ruby: ["ruby:2.7", "ruby:3.0", "ruby:3.1", "ruby:latest"]
          name: actionview-ujs-<< matrix.ruby >>
          gem: actionview
          command: rake test:ujs
      - test-job:
          matrix:
            parameters:
              ruby: ["ruby:2.7", "ruby:3.0", "ruby:3.1", "ruby:latest"]
          name: activestorage-<< matrix.ruby >>
          gem: activestorage
      - test-job:
          matrix:
            parameters:
              ruby: ["ruby:2.7", "ruby:3.0", "ruby:3.1", "ruby:latest"]
          name: activesupport-<< matrix.ruby >>
          gem: activesupport
      - test-job:
          matrix:
            parameters:
              ruby: ["ruby:2.7", "ruby:3.0", "ruby:3.1", "ruby:latest"]
          name: guides-<< matrix.ruby >>
          gem: guides
      - test-job:
          matrix:
            parameters:
              ruby: ["ruby:2.7", "ruby:3.0", "ruby:3.1", "ruby:latest"]
          name: activejob-<< matrix.ruby >>
          gem: activejob
      - test-job:
          matrix:
            parameters:
              ruby: ["ruby:2.7", "ruby:3.0", "ruby:3.1", "ruby:latest"]
          name: activemodel-<< matrix.ruby >>
          gem: activemodel
      - test-job:
          matrix:
            parameters:
              ruby: ["ruby:2.7", "ruby:3.0", "ruby:3.1", "ruby:latest"]
          name: railties-<< matrix.ruby >>
          gem: railties
          nodes: 12
      - test-job:
          matrix:
            parameters:
              ruby: ["ruby:2.7", "ruby:3.0", "ruby:3.1", "ruby:latest"]
          name: activerecord-mysql2-<< matrix.ruby >>
          gem: activerecord
          command: rake db:mysql:rebuild mysql2:test
      - test-job:
          matrix:
            parameters:
              ruby: ["ruby:2.7", "ruby:3.0", "ruby:3.1", "ruby:latest"]
          name: activrecord-mysql2-mariadb-<< matrix.ruby >>
          gem: activerecord
          command: rake db:mysql:rebuild mysql2:test
          mysql: mariadb:latest
      - test-job:
          matrix:
            parameters:
              ruby: ["ruby:2.7", "ruby:3.0", "ruby:3.1", "ruby:latest"]
          name: activrecord-mysql2-prepared-statements-<< matrix.ruby >>
          gem: activerecord
          command: rake db:mysql:rebuild mysql2:test
          mysql_prepared_statements: true
      - test-job:
          matrix:
            parameters:
              ruby: ["ruby:2.7", "ruby:3.0", "ruby:3.1", "ruby:latest"]
          name: activerecord-postgresql-<< matrix.ruby >>
          gem: activerecord
          command: rake db:postgresql:rebuild postgresql:test
      - test-job:
          matrix:
            parameters:
              ruby: ["ruby:2.7", "ruby:3.0", "ruby:3.1", "ruby:latest"]
          name: activerecord-sqlite3-<< matrix.ruby >>
          gem: activerecord
          command: rake sqlite3:test
      - test-job:
          matrix:
            parameters:
              ruby: ["ruby:2.7", "ruby:3.0", "ruby:3.1", "ruby:latest"]
          name: activerecord-sqlite3_mem-<< matrix.ruby >>
          gem: activerecord
          command: rake sqlite3_mem:test
      - test-job:
          matrix:
            parameters:
              ruby: ["ruby:2.7", "ruby:3.0", "ruby:3.1", "ruby:latest"]
          name: activrecord-mysql2-isolated-<< matrix.ruby >>
          gem: activerecord
          command: rake db:mysql:rebuild mysql2:isolated_test
          nodes: 5
      - test-job:
          matrix:
            parameters:
              ruby: ["ruby:2.7", "ruby:3.0", "ruby:3.1", "ruby:latest"]
          name: activerecord-postgresql-isolated-<< matrix.ruby >>
          gem: activerecord
          command: rake db:postgresql:rebuild postgresql:isolated_test
          nodes: 5
      - test-job:
          matrix:
            parameters:
              ruby: ["ruby:2.7", "ruby:3.0", "ruby:3.1", "ruby:latest"]
          name: activerecord-sqlite3-isolated-<< matrix.ruby >>
          gem: activerecord
          command: rake sqlite3:isolated_test
          nodes: 5
      - test-job:
          matrix:
            parameters:
              ruby: ["ruby:2.7", "ruby:3.0", "ruby:3.1", "ruby:latest"]
          name: actionmailer-isolated-<< matrix.ruby >>
          gem: actionmailer
          command: rake test:isolated
      - test-job:
          matrix:
            parameters:
              ruby: ["ruby:2.7", "ruby:3.0", "ruby:3.1", "ruby:latest"]
          name: actionpack-isolated-<< matrix.ruby >>
          gem: actionpack
          command: rake test:isolated
      - test-job:
          matrix:
            parameters:
              ruby: ["ruby:2.7", "ruby:3.0", "ruby:3.1", "ruby:latest"]
          name: actionview-isolated-<< matrix.ruby >>
          gem: actionview
          command: rake test:isolated
      - test-job:
          matrix:
            parameters:
              ruby: ["ruby:2.7", "ruby:3.0", "ruby:3.1", "ruby:latest"]
          name: activejob-isolated-<< matrix.ruby >>
          gem: activejob
          command: rake test:isolated
      - test-job:
          matrix:
            parameters:
              ruby: ["ruby:2.7", "ruby:3.0", "ruby:3.1", "ruby:latest"]
          name: activemodel-isolated-<< matrix.ruby >>
          gem: activemodel
          command: rake test:isolated
      - test-job:
          matrix:
            parameters:
              ruby: ["ruby:2.7", "ruby:3.0", "ruby:3.1", "ruby:latest"]
          name: activesupport-isolated-<< matrix.ruby >>
          gem: activesupport
          command: rake test:isolated
