# rubies:
#   - 3.1
#   - 3.0
#   - 2.7

# rails:
#   - actioncable
#     - integration
#   - activejob
#     - integration

version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.2.3

commands:
  run-tests:
    parameters:
      gem:
        type: string
      command:
        type: string
        default: rake test
    steps:
      - run:
          name: Run tests
          command: |
            env COMPOSE_TLS_VERSION=TLSv1_2 \
            docker-compose -f .circleci/docker-compose.yml run app runner << parameters.gem >> "<< parameters.command >>"

  bundle-restore:
    parameters:
      ruby:
        type: string
        default: latest
    steps:
      - restore_cache:
          keys:
            - gem-cache-v1-ruby-<< parameters.ruby >>-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - gem-cache-v1-ruby-<< parameters.ruby >>-{{ .Branch }}
            - gem-cache-v1-ruby-<< parameters.ruby >>

  bundle-install:
    parameters:
      ruby:
        type: string
        default: latest
    steps:
      - bundle-restore:
          ruby: << parameters.ruby >>
      - run:
          name: Bundle install
          command: |
            env COMPOSE_TLS_VERSION=TLSv1_2 \
            docker-compose -f .circleci/docker-compose.yml run app bundle install --path vendor/bundle
      - save_cache:
          key: gem-cache-v1-ruby-<< parameters.ruby >>-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundlers.ruby

jobs:
  build-image:
    parameters:
      ruby:
        type: string
        default: latest
    machine:
      image: ubuntu-2004:202111-02
      docker_layer_caching: true
      resource_class: large
    environment:
      CACHE_IMAGE: zzak/rails-ci
      DOCKER_BUILDKIT: 1
      RUBY_IMAGE: ruby:<< parameters.ruby >>
    steps:
      - checkout
      - run:
          name: Login to docker hub
          command: docker login -u $REGISTRY_USER -p $REGISTRY_PASS
      - run:
          name: Build application Docker image
          command: |
            export DOCKER_TAG=v1-ruby-<< parameters.ruby >>-dev

            docker build \
              --cache-from=$CACHE_IMAGE:$DOCKER_TAG \
              --tag=$CACHE_IMAGE:$DOCKER_TAG \
              --build-arg BUILDKIT_INLINE_CACHE=1 \
              --build-arg RUBY_IMAGE=$RUBY_IMAGE \
              -f .circleci/Dockerfile .
      - run:
          name: Push to docker hub
          command: |
            export DOCKER_TAG=v1-ruby-<< parameters.ruby >>-dev
            docker push $CACHE_IMAGE:$DOCKER_TAG

  bundle-install:
    parameters:
      ruby:
        type: string
        default: latest
    machine:
      image: ubuntu-2004:202111-02
      docker_layer_caching: true
      resource_class: large
    environment:
      APP_IMAGE_TAG: zzak/rails-ci:v1-ruby-<< parameters.ruby >>-dev
      RUBY_IMAGE: << parameters.ruby >>
    steps:
      - checkout
      - run:
          name: Pull build image
          command: docker pull $APP_IMAGE_TAG
      - bundle-install:
          ruby: << parameters.ruby >>

  test-job:
    parameters:
      gem:
        type: string
      command:
        type: string
        default: rake test
      ruby:
        type: string
        default: latest
      mysql:
        type: string
        default: mysql:latest
      mysql_prepared_statements:
        type: boolean
        default: false
      nodes:
        type: integer
        default: 1
    machine:
      image: ubuntu-2004:202111-02
      docker_layer_caching: true
      resource_class: large
    parallelism: << parameters.nodes >>
    environment:
      APP_IMAGE_TAG: zzak/rails-ci:v1-ruby-<< parameters.ruby >>-dev
      RUBY_IMAGE: << parameters.ruby >>
      MYSQL_IMAGE: << parameters.mysql >>
      MYSQL_PREPARED_STATEMENTS: << parameters.mysql_prepared_statements >>
    steps:
      - checkout
      - run:
          name: Pull build image
          command: docker pull $APP_IMAGE_TAG
      - run-tests:
          gem: << parameters.gem >>
          command: << parameters.command >>
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports

workflows:
  version: 2
  test:
    jobs:
      - build-image:
         matrix:
           parameters:
             ruby: ["2.7", "3.0", "3.1", "latest"]
      - bundle-install:
          matrix:
            parameters:
              ruby: ["2.7", "3.0", "3.1", "latest"]
          name: bundle-install-<< matrix.ruby >>
          requires:
            - build-image-<< matrix.ruby >>
      - test-job:
          matrix:
            parameters:
              ruby: ["2.7", "3.0", "3.1", "latest"]
          name: actioncable-<< matrix.ruby >>
          gem: actioncable
          requires:
            - bundle-install-<< matrix.ruby >>
      #- actioncable-integration
      - test-job:
          matrix:
            parameters:
              ruby: ["2.7", "3.0", "3.1", "latest"]
          name: actionmailbox-<< matrix.ruby >>
          gem: actionmailbox
          requires:
            - bundle-install-<< matrix.ruby >>
      - test-job:
          matrix:
            parameters:
              ruby: ["2.7", "3.0", "3.1", "latest"]
          name: actionmailer-<< matrix.ruby >>
          gem: actionmailer
          requires:
            - bundle-install-<< matrix.ruby >>
      - test-job:
          matrix:
            parameters:
              ruby: ["2.7", "3.0", "3.1", "latest"]
          name: actionpack-<< matrix.ruby >>
          gem: actionpack
          requires:
            - bundle-install-<< matrix.ruby >>
      - test-job:
          matrix:
            parameters:
              ruby: ["2.7", "3.0", "3.1", "latest"]
          name: actiontext-<< matrix.ruby >>
          gem: actiontext
          requires:
            - bundle-install-<< matrix.ruby >>
      - test-job:
          matrix:
            parameters:
              ruby: ["2.7", "3.0", "3.1", "latest"]
          name: actionview-<< matrix.ruby >>
          gem: actionview
          requires:
            - bundle-install-<< matrix.ruby >>
      - test-job:
          matrix:
            parameters:
              ruby: ["2.7", "3.0", "3.1", "latest"]
          name: actionview-ujs-<< matrix.ruby >>
          gem: actionview
          command: rake test:ujs
          requires:
            - bundle-install-<< matrix.ruby >>
      - test-job:
          matrix:
            parameters:
              ruby: ["2.7", "3.0", "3.1", "latest"]
          name: activestorage-<< matrix.ruby >>
          gem: activestorage
          requires:
            - bundle-install-<< matrix.ruby >>
      - test-job:
          matrix:
            parameters:
              ruby: ["2.7", "3.0", "3.1", "latest"]
          name: activesupport-<< matrix.ruby >>
          gem: activesupport
          requires:
            - bundle-install-<< matrix.ruby >>
      - test-job:
          matrix:
            parameters:
              ruby: ["2.7", "3.0", "3.1", "latest"]
          name: guides-<< matrix.ruby >>
          gem: guides
          requires:
            - bundle-install-<< matrix.ruby >>
      - test-job:
          matrix:
            parameters:
              ruby: ["2.7", "3.0", "3.1", "latest"]
          name: activejob-<< matrix.ruby >>
          gem: activejob
          requires:
            - bundle-install-<< matrix.ruby >>
      - test-job:
          matrix:
            parameters:
              ruby: ["2.7", "3.0", "3.1", "latest"]
          name: activemodel-<< matrix.ruby >>
          gem: activemodel
          requires:
            - bundle-install-<< matrix.ruby >>
      - test-job:
          matrix:
            parameters:
              ruby: ["2.7", "3.0", "3.1", "latest"]
          name: railties-<< matrix.ruby >>
          gem: railties
          nodes: 12
          requires:
            - bundle-install-<< matrix.ruby >>
      - test-job:
          matrix:
            parameters:
              ruby: ["2.7", "3.0", "3.1", "latest"]
          name: activerecord-mysql2-<< matrix.ruby >>
          gem: activerecord
          command: rake db:mysql:rebuild mysql2:test
          requires:
            - bundle-install-<< matrix.ruby >>
      - test-job:
          matrix:
            parameters:
              ruby: ["2.7", "3.0", "3.1", "latest"]
          name: activrecord-mysql2-mariadb-<< matrix.ruby >>
          gem: activerecord
          command: rake db:mysql:rebuild mysql2:test
          mysql: mariadb:latest
          requires:
            - bundle-install-<< matrix.ruby >>
      - test-job:
          matrix:
            parameters:
              ruby: ["2.7", "3.0", "3.1", "latest"]
          name: activrecord-mysql2-prepared-statements-<< matrix.ruby >>
          gem: activerecord
          command: rake db:mysql:rebuild mysql2:test
          mysql_prepared_statements: true
          requires:
            - bundle-install-<< matrix.ruby >>
      - test-job:
          matrix:
            parameters:
              ruby: ["2.7", "3.0", "3.1", "latest"]
          name: activerecord-postgresql-<< matrix.ruby >>
          gem: activerecord
          command: rake db:postgresql:rebuild postgresql:test
          requires:
            - bundle-install-<< matrix.ruby >>
      - test-job:
          matrix:
            parameters:
              ruby: ["2.7", "3.0", "3.1", "latest"]
          name: activerecord-sqlite3-<< matrix.ruby >>
          gem: activerecord
          command: rake sqlite3:test
          requires:
            - bundle-install-<< matrix.ruby >>
      - test-job:
          matrix:
            parameters:
              ruby: ["2.7", "3.0", "3.1", "latest"]
          name: activerecord-sqlite3_mem-<< matrix.ruby >>
          gem: activerecord
          command: rake sqlite3_mem:test
          requires:
            - bundle-install-<< matrix.ruby >>
      - test-job:
          matrix:
            parameters:
              ruby: ["2.7", "3.0", "3.1", "latest"]
          name: activrecord-mysql2-isolated-<< matrix.ruby >>
          gem: activerecord
          command: rake db:mysql:rebuild mysql2:isolated_test
          nodes: 5
          requires:
            - bundle-install-<< matrix.ruby >>
      - test-job:
          matrix:
            parameters:
              ruby: ["2.7", "3.0", "3.1", "latest"]
          name: activerecord-postgresql-isolated-<< matrix.ruby >>
          gem: activerecord
          command: rake db:postgresql:rebuild postgresql:isolated_test
          nodes: 5
          requires:
            - bundle-install-<< matrix.ruby >>
      - test-job:
          matrix:
            parameters:
              ruby: ["2.7", "3.0", "3.1", "latest"]
          name: activerecord-sqlite3-isolated-<< matrix.ruby >>
          gem: activerecord
          command: rake sqlite3:isolated_test
          nodes: 5
          requires:
            - bundle-install-<< matrix.ruby >>
      - test-job:
          matrix:
            parameters:
              ruby: ["2.7", "3.0", "3.1", "latest"]
          name: actionmailer-isolated-<< matrix.ruby >>
          gem: actionmailer
          command: rake test:isolated
          requires:
            - bundle-install-<< matrix.ruby >>
      - test-job:
          matrix:
            parameters:
              ruby: ["2.7", "3.0", "3.1", "latest"]
          name: actionpack-isolated-<< matrix.ruby >>
          gem: actionpack
          command: rake test:isolated
          requires:
            - bundle-install-<< matrix.ruby >>
      - test-job:
          matrix:
            parameters:
              ruby: ["2.7", "3.0", "3.1", "latest"]
          name: actionview-isolated-<< matrix.ruby >>
          gem: actionview
          command: rake test:isolated
          requires:
            - bundle-install-<< matrix.ruby >>
      - test-job:
          matrix:
            parameters:
              ruby: ["2.7", "3.0", "3.1", "latest"]
          name: activejob-isolated-<< matrix.ruby >>
          gem: activejob
          command: rake test:isolated
          requires:
            - bundle-install-<< matrix.ruby >>
      - test-job:
          matrix:
            parameters:
              ruby: ["2.7", "3.0", "3.1", "latest"]
          name: activemodel-isolated-<< matrix.ruby >>
          gem: activemodel
          command: rake test:isolated
          requires:
            - bundle-install-<< matrix.ruby >>
      - test-job:
          matrix:
            parameters:
              ruby: ["2.7", "3.0", "3.1", "latest"]
          name: activesupport-isolated-<< matrix.ruby >>
          gem: activesupport
          command: rake test:isolated
          requires:
            - bundle-install-<< matrix.ruby >>
