# rubies:
#   - 3.1
#   - 3.0
#   - 2.7

# rails:
#   - actioncable
#     - integration
#   - actionmailbox
#   - actionmailer
#   - actionpack
#   - actiontext
#   - actionview
#     - ujs
#   - activemodel
#   - activerecord
#     - mysql2
#     - postgresql
#     - sqlite3
#     - sqlite3_mem
#   - activestorage
#   - activesupport
#   - guides
#   - railties
#   - activejob
#     - integration

version: 2.1

jobs:
  actioncable:
    docker:
      - image: cimg/ruby:3.1
      - image: circleci/redis
    steps:
      - checkout
      - run:
          name: Bundle install
          command: rm Gemfile.lock && bundle install
      - run:
          name: Test
          command: cd actioncable && bin/test

  actioncable-integration:
    docker:
      - image: cimg/ruby:3.1-node
      - image: circleci/redis
    steps:
      - checkout
      - run:
          name: Bundle install
          command: rm Gemfile.lock && bundle install
      - run:
          name: Test
          command: cd actioncable && bundle exec rake test:integration

  actionmailbox:
    docker:
      - image: cimg/ruby:3.1
    steps:
      - checkout
      - run:
          name: Bundle install
          command: rm Gemfile.lock && bundle install
      - run:
          name: Test
          command: cd actionmailbox && bin/test

  actionmailer:
    docker:
      - image: cimg/ruby:3.1
    steps:
      - checkout
      - run:
          name: Bundle install
          command: rm Gemfile.lock && bundle install
      - run:
          name: Test
          command: cd actionmailer && bin/test

workflows:
  version: 2
  test:
    jobs:
      - actioncable
      - actioncable-integration
      - actionmailbox
      - actionmailer


