# rubies:
#   - 3.1
#   - 3.0
#   - 2.7

# rails:
#   - actioncable
#     - integration
#   - activejob
#     - integration
#   - activerecord-isolated
#     - mysql2
#     - postgresql
#     - sqlite3
#     - sqlite3_mem

version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.2.3

commands:
  run-tests:
    parameters:
      gem:
        type: string
      command:
        type: string
        default: rake test
    steps:
      - run:
          name: Run tests
          command: |
            env COMPOSE_TLS_VERSION=TLSv1_2 \
            docker-compose -f .circleci/docker-compose.yml run app runner << parameters.gem >> "<< parameters.command >>"

jobs:
  test-job:
    parameters:
      gem:
        type: string
      command:
        type: string
        default: rake test
      ruby:
        type: string
        default: ruby:latest
      mysql:
        type: string
        default: mysql:latest
      mysql_prepared_statements:
        type: boolean
        default: false
      nodes:
        type: integer
        default: 1
    machine:
      image: ubuntu-2004:202111-02
      docker_layer_caching: true
      resource_class: large
    parallelism: << parameters.nodes >>
    environment:
      RUBY_IMAGE: << parameters.ruby >>
      MYSQL_IMAGE: << parameters.mysql >>
      MYSQL_PREPARED_STATEMENTS: << parameters.mysql_prepared_statements >>
    steps:
      - checkout
      - run:
          name: Make cache directory
          command: |
            sudo mkdir /caches
            sudo chown -R $USER:$USER /caches
      - restore_cache:
          keys:
            - v1-<< parameters.ruby >>-{{ .Branch }}
          paths:
            - /caches/app.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=app --build-arg MYSQL_IMAGE=$MYSQL_IMAGE --build-arg RUBY_IMAGE=$RUBY_IMAGE -t app -f .circleci/Dockerfile .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/app.tar app
      - save_cache:
          key: v1-<< parameters.ruby >>-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/app.tar
      - run-tests:
          gem: << parameters.gem >>
          command: << parameters.command >>
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports

workflows:
  version: 2
  test:
    jobs:
      - test-job:
          name: actioncable
          gem: actioncable
      #- actioncable-integration
      - test-job:
          name: actionmailbox
          gem: actionmailbox
      - test-job:
          name: actionmailer
          gem: actionmailer
      - test-job:
          name: actionpack
          gem: actionpack
      - test-job:
          name: actiontext
          gem: actiontext
      - test-job:
          name: actionview
          gem: actionview
      - test-job:
          name: actionview-ujs
          gem: actionview
          command: rake test:ujs
      - test-job:
          name: activestorage
          gem: activestorage
      - test-job:
          name: activesupport
          gem: activesupport
      - test-job:
          name: guides
          gem: guides
      - test-job:
          name: activejob
          gem: activejob
      - test-job:
          name: activemodel
          gem: activemodel
      - test-job:
          name: railties
          gem: railties
          nodes: 12
      - test-job:
          name: activerecord-mysql2
          gem: activerecord
          command: rake db:mysql:rebuild mysql2:test
      - test-job:
          name: activrecord-mysql2-mariadb
          gem: activerecord
          command: rake db:mysql:rebuild mysql2:test
          mysql: mariadb:latest
      - test-job:
          name: activrecord-mysql2-prepared-statements
          gem: activerecord
          command: rake db:mysql:rebuild mysql2:test
          mysql_prepared_statements: true
      - test-job:
          name: activerecord-postgresql
          gem: activerecord
          command: rake db:postgresql:rebuild postgresql:test
      - test-job:
          name: activerecord-sqlite3
          gem: activerecord
          command: rake sqlite3:test
      - test-job:
          name: activerecord-sqlite3_mem
          gem: activerecord
          command: rake sqlite3_mem:test
      - test-job:
          name: activrecord-mysql2-isolated
          gem: activerecord
          command: rake db:mysql:rebuild mysql2:isolated_test
          nodes: 5
      - test-job:
          name: activerecord-postgresql-isolated
          gem: activerecord
          command: rake db:postgresql:rebuild postgresql:isolated_test
          nodes: 5
      - test-job:
          name: activerecord-sqlite3-isolated
          gem: activerecord
          command: rake sqlite3:isolated_test
          nodes: 5
      - test-job:
          name: actionmailer-isolated
          gem: actionmailer
          command: rake test:isolated
      - test-job:
          name: actionpack-isolated
          gem: actionpack
          command: rake test:isolated
      - test-job:
          name: actionview-isolated
          gem: actionview
          command: rake test:isolated
      - test-job:
          name: activejob-isolated
          gem: activejob
          command: rake test:isolated
      - test-job:
          name: activemodel-isolated
          gem: activemodel
          command: rake test:isolated
      - test-job:
          name: activesupport-isolated
          gem: activesupport
          command: rake test:isolated
