# rubies:
#   - 3.1
#   - 3.0
#   - 2.7

# rails:
#   - actioncable
#     - integration
#   - actionmailbox
#   - actionmailer
#   - actionpack
#   - actiontext
#   - actionview
#     - ujs
#   - activemodel
#   - activerecord
#     - mysql2
#     - postgresql
#     - sqlite3
#     - sqlite3_mem
#   - activestorage
#   - activesupport
#   - guides
#   - railties
#   - activejob
#     - integration

version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.2.3

executors:
  base:
    docker:
      - image: docker:17.05.0-ce-git
  dbs:
    docker:
      - image: docker:17.05.0-ce-git
      - image: postgres:alpine
        environment:
          - POSTGRES_HOST_AUTH_METHOD: "trust"
      - image: mysql:latest
        command: "--default-authentication-plugin=mysql_native_password"
        environment:
          - MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  services:
    docker:
      - image: docker:17.05.0-ce-git
      - image: redis:alpine
      - image: rabbitmq:alpine
      - image: memcached:alpine
  redis:
    docker:
      - image: docker:17.05.0-ce-git
      - image: redis:alpine

jobs:
  test-job:
    parameters:
      gem:
        type: string
      exe:
        type: executor
        default: base
      command:
        type: string
        default: bundle exec rake test
    executor: << parameters.exe >>
    working_directory: /app
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1
            pip install \
              docker-compose==1.12.0
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/app.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=app -t app -f .circleci/Dockerfile .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/app.tar app
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/app.tar
      - run:
          name: Run tests
          command: |
            export COMPOSE_TLS_VERSION=TLSv1_2 && \
            docker-compose -f .circleci/docker-compose.yml run app bash -c \
              "rm Gemfile.lock && bundle install && \
              cd << parameters.gem >> && << parameters.command >>"

  actioncable-integration:
    docker:
      - image: cimg/ruby:3.1-browsers
      - image: circleci/redis
    steps:
      - checkout
      - browser-tools/install-browser-tools
      - run:
          name: Bundle install
          command: rm Gemfile.lock && bundle install
      - run:
          name: Yarn install
          command: yarn install
      - run:
          name: Test
          command: cd actioncable && bundle exec rake test:integration

workflows:
  version: 2
  test:
    jobs:
      - test-job:
          name: actioncable
          gem: actioncable
          exe: redis
      #- actioncable-integration
      - test-job:
          name: actionmailbox
          gem: actionmailbox
      - test-job:
          name: actionmailer
          gem: actionmailer
      - test-job:
          name: actionpack
          gem: actionpack
      - test-job:
          name: actiontext
          gem: actiontext
      - test-job:
          name: actionview
          gem: actionview
      - test-job:
          name: activestorage
          gem: activestorage
      - test-job:
          name: activesupport
          gem: activesupport
          exe: services
      - test-job:
          name: guides
          gem: guides
      - test-job:
          name: activejob
          gem: activejob
      - test-job:
          name: activemodel
          gem: activemodel
      - test-job:
          name: activerecord-mysql2
          gem: activerecord
          exe: dbs
          command: bundle exec rake db:mysql:build mysql2:test
      - test-job:
          name: activerecord-postgresql
          gem: activerecord
          exe: dbs
          command: bundle exec rake db:postgresql:build postgresql:test
      - test-job:
          name: activerecord-sqlite3
          gem: activerecord
          exe: dbs
          command: bundle exec rake sqlite3:test
      - test-job:
          name: activerecord-sqlite3_mem
          gem: activerecord-sqlite3_mem
          exe: dbs
          command: bundle exec rake sqlite3_mem:test

