# rubies:
#   - 3.1
#   - 3.0
#   - 2.7

# rails:
#   - actioncable
#     - integration
#   - activejob
#     - integration

version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.2.3

commands:
  run-tests:
    parameters:
      gem:
        type: string
      command:
        type: string
        default: rake test
    steps:
      - run:
          name: Run tests
          command: runner << parameters.gem >> "<< parameters.command >>"

jobs:
  build-image:
    parameters:
      ruby:
        type: string
        default: latest
    machine:
      image: ubuntu-2004:202111-02
      docker_layer_caching: true
      resource_class: large
    environment:
      CACHE_IMAGE: zzak/rails-ci
      DOCKER_BUILDKIT: 1
      RUBY_IMAGE: ruby:<< parameters.ruby >>
    steps:
      - checkout
      - run:
          name: Login to docker hub
          command: docker login -u $REGISTRY_USER -p $REGISTRY_PASS
      - run:
          name: Build application Docker image
          command: |
            export DOCKER_TAG=v1-ruby-<< parameters.ruby >>-$CIRCLE_BRANCH

            docker build \
              --cache-from=$CACHE_IMAGE:$DOCKER_TAG \
              --tag=$DOCKER_TAG \
              --build-arg BUILDKIT_INLINE_CACHE=1 \
              --build-arg RUBY_IMAGE=$RUBY_IMAGE \
              -f .circleci/Dockerfile .
      - run:
          name: Push to docker hub
          command: |
            export DOCKER_TAG=v1-ruby-<< parameters.ruby >>-$CIRCLE_BRANCH
            docker push $CACHE_IMAGE:$DOCKER_TAG

  test-job:
    parameters:
      gem:
        type: string
      command:
        type: string
        default: rake test
      ruby:
        type: string
        default: latest
      mysql:
        type: string
        default: mysql:latest
      mysql_prepared_statements:
        type: boolean
        default: false
      nodes:
        type: integer
        default: 1
    docker:
      - image: zzak/rails-ci:v1-ruby-<< parameters.ruby >>-{{ .Branch }}
      - image: redis:alpine
      - image: << parameters.mysql >>
        command: "--default-authentication-plugin=mysql_native_password"
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        #volumes:
          #- "./mysql-initdb.d:/docker-entrypoint-initdb.d"
      - image: memcached:alpine
      - image: "${POSTGRES_IMAGE-postgres:alpine}"
        environment:
          POSTGRES_HOST_AUTH_METHOD: "trust"

      - image: rabbitmq:alpine
      - image: selenium/standalone-chrome:latest

    resource_class: large
    parallelism: << parameters.nodes >>
    environment:
      MYSQL_PREPARED_STATEMENTS: << parameters.mysql_prepared_statements >>

      MEMCACHE_SERVERS: "memcached:11211"
      MYSQL_HOST: mysql
      PGHOST: postgres
      PGUSER: postgres
      QC_DATABASE_URL: "postgres://postgres@postgres/active_jobs_qc_int_test"
      QUE_DATABASE_URL: "postgres://postgres@postgres/active_jobs_que_int_test"
      RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672"
      REDIS_URL: "redis://redis:6379/1"
      SELENIUM_DRIVER_URL: "http://chrome:4444/wd/hub"

      AWAIT_redis: tcp://redis:6379
      AWAIT_memcached: tcp://memcached:11211
      AWAIT_mysql: tcp://mysql:3306
      AWAIT_postgres: postgres://postgres@postgres:5432/postgres
      AWAIT_rabbitmq: tcp://rabbitmq:5672
      AWAIT_chrome: tcp://chrome:4444

    steps:
      - checkout
      - run: await-all
      - run-tests:
          gem: << parameters.gem >>
          command: << parameters.command >>
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports

workflows:
  version: 2
  test:
    jobs:
      - build-image:
         matrix:
           parameters:
             ruby: ["2.7", "3.0", "3.1", "latest"]
      - test-job:
          matrix:
            parameters:
              ruby: ["2.7", "3.0", "3.1", "latest"]
          name: actioncable-<< matrix.ruby >>
          gem: actioncable
          requires:
            - build-image-<< matrix.ruby >>
      #- actioncable-integration
      - test-job:
          matrix:
            parameters:
              ruby: ["2.7", "3.0", "3.1", "latest"]
          name: actionmailbox-<< matrix.ruby >>
          gem: actionmailbox
          requires:
            - build-image-<< matrix.ruby >>
      - test-job:
          matrix:
            parameters:
              ruby: ["2.7", "3.0", "3.1", "latest"]
          name: actionmailer-<< matrix.ruby >>
          gem: actionmailer
          requires:
            - build-image-<< matrix.ruby >>
      - test-job:
          matrix:
            parameters:
              ruby: ["2.7", "3.0", "3.1", "latest"]
          name: actionpack-<< matrix.ruby >>
          gem: actionpack
          requires:
            - build-image-<< matrix.ruby >>
      - test-job:
          matrix:
            parameters:
              ruby: ["2.7", "3.0", "3.1", "latest"]
          name: actiontext-<< matrix.ruby >>
          gem: actiontext
          requires:
            - build-image-<< matrix.ruby >>
      - test-job:
          matrix:
            parameters:
              ruby: ["2.7", "3.0", "3.1", "latest"]
          name: actionview-<< matrix.ruby >>
          gem: actionview
          requires:
            - build-image-<< matrix.ruby >>
      - test-job:
          matrix:
            parameters:
              ruby: ["2.7", "3.0", "3.1", "latest"]
          name: actionview-ujs-<< matrix.ruby >>
          gem: actionview
          command: rake test:ujs
          requires:
            - build-image-<< matrix.ruby >>
      - test-job:
          matrix:
            parameters:
              ruby: ["2.7", "3.0", "3.1", "latest"]
          name: activestorage-<< matrix.ruby >>
          gem: activestorage
          requires:
            - build-image-<< matrix.ruby >>
      - test-job:
          matrix:
            parameters:
              ruby: ["2.7", "3.0", "3.1", "latest"]
          name: activesupport-<< matrix.ruby >>
          gem: activesupport
          requires:
            - build-image-<< matrix.ruby >>
      - test-job:
          matrix:
            parameters:
              ruby: ["2.7", "3.0", "3.1", "latest"]
          name: guides-<< matrix.ruby >>
          gem: guides
          requires:
            - build-image-<< matrix.ruby >>
      - test-job:
          matrix:
            parameters:
              ruby: ["2.7", "3.0", "3.1", "latest"]
          name: activejob-<< matrix.ruby >>
          gem: activejob
          requires:
            - build-image-<< matrix.ruby >>
      - test-job:
          matrix:
            parameters:
              ruby: ["2.7", "3.0", "3.1", "latest"]
          name: activemodel-<< matrix.ruby >>
          gem: activemodel
          requires:
            - build-image-<< matrix.ruby >>
      - test-job:
          matrix:
            parameters:
              ruby: ["2.7", "3.0", "3.1", "latest"]
          name: railties-<< matrix.ruby >>
          gem: railties
          nodes: 12
          requires:
            - build-image-<< matrix.ruby >>
      - test-job:
          matrix:
            parameters:
              ruby: ["2.7", "3.0", "3.1", "latest"]
          name: activerecord-mysql2-<< matrix.ruby >>
          gem: activerecord
          command: rake db:mysql:rebuild mysql2:test
          requires:
            - build-image-<< matrix.ruby >>
      - test-job:
          matrix:
            parameters:
              ruby: ["2.7", "3.0", "3.1", "latest"]
          name: activrecord-mysql2-mariadb-<< matrix.ruby >>
          gem: activerecord
          command: rake db:mysql:rebuild mysql2:test
          mysql: mariadb:latest
          requires:
            - build-image-<< matrix.ruby >>
      - test-job:
          matrix:
            parameters:
              ruby: ["2.7", "3.0", "3.1", "latest"]
          name: activrecord-mysql2-prepared-statements-<< matrix.ruby >>
          gem: activerecord
          command: rake db:mysql:rebuild mysql2:test
          mysql_prepared_statements: true
          requires:
            - build-image-<< matrix.ruby >>
      - test-job:
          matrix:
            parameters:
              ruby: ["2.7", "3.0", "3.1", "latest"]
          name: activerecord-postgresql-<< matrix.ruby >>
          gem: activerecord
          command: rake db:postgresql:rebuild postgresql:test
          requires:
            - build-image-<< matrix.ruby >>
      - test-job:
          matrix:
            parameters:
              ruby: ["2.7", "3.0", "3.1", "latest"]
          name: activerecord-sqlite3-<< matrix.ruby >>
          gem: activerecord
          command: rake sqlite3:test
          requires:
            - build-image-<< matrix.ruby >>
      - test-job:
          matrix:
            parameters:
              ruby: ["2.7", "3.0", "3.1", "latest"]
          name: activerecord-sqlite3_mem-<< matrix.ruby >>
          gem: activerecord
          command: rake sqlite3_mem:test
          requires:
            - build-image-<< matrix.ruby >>
      - test-job:
          matrix:
            parameters:
              ruby: ["2.7", "3.0", "3.1", "latest"]
          name: activrecord-mysql2-isolated-<< matrix.ruby >>
          gem: activerecord
          command: rake db:mysql:rebuild mysql2:isolated_test
          nodes: 5
          requires:
            - build-image-<< matrix.ruby >>
      - test-job:
          matrix:
            parameters:
              ruby: ["2.7", "3.0", "3.1", "latest"]
          name: activerecord-postgresql-isolated-<< matrix.ruby >>
          gem: activerecord
          command: rake db:postgresql:rebuild postgresql:isolated_test
          nodes: 5
          requires:
            - build-image-<< matrix.ruby >>
      - test-job:
          matrix:
            parameters:
              ruby: ["2.7", "3.0", "3.1", "latest"]
          name: activerecord-sqlite3-isolated-<< matrix.ruby >>
          gem: activerecord
          command: rake sqlite3:isolated_test
          nodes: 5
          requires:
            - build-image-<< matrix.ruby >>
      - test-job:
          matrix:
            parameters:
              ruby: ["2.7", "3.0", "3.1", "latest"]
          name: actionmailer-isolated-<< matrix.ruby >>
          gem: actionmailer
          command: rake test:isolated
          requires:
            - build-image-<< matrix.ruby >>
      - test-job:
          matrix:
            parameters:
              ruby: ["2.7", "3.0", "3.1", "latest"]
          name: actionpack-isolated-<< matrix.ruby >>
          gem: actionpack
          command: rake test:isolated
          requires:
            - build-image-<< matrix.ruby >>
      - test-job:
          matrix:
            parameters:
              ruby: ["2.7", "3.0", "3.1", "latest"]
          name: actionview-isolated-<< matrix.ruby >>
          gem: actionview
          command: rake test:isolated
          requires:
            - build-image-<< matrix.ruby >>
      - test-job:
          matrix:
            parameters:
              ruby: ["2.7", "3.0", "3.1", "latest"]
          name: activejob-isolated-<< matrix.ruby >>
          gem: activejob
          command: rake test:isolated
          requires:
            - build-image-<< matrix.ruby >>
      - test-job:
          matrix:
            parameters:
              ruby: ["2.7", "3.0", "3.1", "latest"]
          name: activemodel-isolated-<< matrix.ruby >>
          gem: activemodel
          command: rake test:isolated
          requires:
            - build-image-<< matrix.ruby >>
      - test-job:
          matrix:
            parameters:
              ruby: ["2.7", "3.0", "3.1", "latest"]
          name: activesupport-isolated-<< matrix.ruby >>
          gem: activesupport
          command: rake test:isolated
          requires:
            - build-image-<< matrix.ruby >>
