# rubies:
#   - 3.1
#   - 3.0
#   - 2.7

# rails:
#   - actioncable
#     - integration
#   - actionmailbox
#   - actionmailer
#   - actionpack
#   - actiontext
#   - actionview
#     - ujs
#   - activemodel
#   - activerecord
#     - mysql2
#     - postgresql
#     - sqlite3
#     - sqlite3_mem
#   - activestorage
#   - activesupport
#   - guides
#   - railties
#   - activejob
#     - integration

version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.2.3

executors:
  base:
    docker:
      - image: cimg/ruby:3.1
  services:
    docker:
      - image: cimg/ruby:3.1-browsers
      - image: circleci/redis
      #- image: bitnami/rabbitmq
      - image: bitnami/memcached
  redis:
    docker:
      - image: cimg/ruby:3.1-browsers
      - image: circleci/redis

jobs:
  test-job:
    parameters:
      gem:
        type: string
      exe:
        type: executor
        default: base
    executor: << parameters.exe >>
    steps:
      - checkout
      - run:
          name: Bundle install
          command: rm Gemfile.lock && bundle install
      - run:
          name: Test
          command: cd << parameters.gem >> && bundle exec rake test

  actioncable-integration:
    docker:
      - image: cimg/ruby:3.1-browsers
      - image: circleci/redis
    steps:
      - checkout
      - browser-tools/install-browser-tools
      - run:
          name: Bundle install
          command: rm Gemfile.lock && bundle install
      - run:
          name: Yarn install
          command: yarn install
      - run:
          name: Test
          command: cd actioncable && bundle exec rake test:integration

workflows:
  version: 2
  test:
    jobs:
      - test-job:
          name: actioncable
          gem: actioncable
          exe: redis
      #- actioncable-integration
      - test-job:
          name: actionmailbox
          gem: actionmailbox
      - test-job:
          name: actionmailer
          gem: actionmailer
      - test-job:
          name: actionpack
          gem: actionpack
      - test-job:
          name: actiontext
          gem: actiontext
      - test-job:
          name: actionview
          gem: actionview
      - test-job:
          name: activestorage
          gem: activestorage
      - test-job:
          name: activesupport
          gem: activesupport
          exe: services
      - test-job:
          name: guides
          gem: guides
      - test-job:
          name: activejob
          gem: activejob



