version: 2.1
setup: true
orbs:
  continuation: circleci/continuation@0.1.0
jobs:
  generate-config:
    docker:
      - image: cimg/ruby:3.1
    steps:
      - checkout
      - run:
          name: Generate Pipeline generated_config.yml file
          command: ruby .circleci/generate-pipeline-config.rb
      - continuation/continue:
          parameters: '{}'
          configuration_path: configs/generated_config.yml
workflows:
  setup-workflow:
    jobs:
      - generate-config
