#!/bin/sh

echo "--- :bundler: Installing Ruby deps" \
    && bundle config set deployment 'true'
    && rm Gemfile.lock && bundle install -j 8

if [ -f package.json ]; then \
    echo "--- :javascript: Installing JavaScript deps" \
    && yarn install --frozen-lockfile --cache-folder ~/.cache/yarn
elif [ -f actionview/package.json ]; then \
    echo "--- :javascript: Installing JavaScript deps" \
    && (cd actionview && npm install); \
fi

if [ -f package.json ]; then \
    echo "--- :javascript: Building JavaScript package" \
    && (cd actionview && yarn build) \
    && if [ -f railties/test/isolation/assets/package.json ]; then \
        (cd railties/test/isolation/assets && yarn install --frozen-lockfile --cache-folder ~/.cache/yarn); \
    fi \
fi
