#!/bin/sh

set -e

dir="$1"
cmd="$2"

echo
echo "--- bundle env"
bundle env
echo "+++  "

if ! [ -d "$PWD/railties/exe" ]; then
  export PATH="$PATH:$PWD/railties/bin"
fi

mysql -h localhost -u root mysql < .circleci/mysql-initdb.d/create.sql

echo "+++ $dir: $cmd"

cd $dir
exec bundle exec /bin/sh -e -c "$cmd"
