name: Debug railtie test on macos

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: system deps
        run: |
          brew update
          brew install openssl libyaml libksba readline zlib \
                       gmp coreutils libffi imagemagick \
                       postgresql mysql zstd

          echo 'export LDFLAGS="-L/opt/homebrew/opt/openssl@3/lib -L/opt/homebrew/opt/zstd/lib"' >> $GITHUB_ENV
          echo 'export CPPFLAGS="-I/opt/homebrew/opt/openssl@3/include -I/opt/homebrew/opt/zstd/include"' >> $GITHUB_ENV
          echo 'export PKG_CONFIG_PATH="/opt/homebrew/opt/openssl@3/lib/pkgconfig:/opt/homebrew/opt/zstd/lib/pkgconfig"' >> $GITHUB_ENV


      - name: setup-ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true

      - name: run test
        run: |
          cd railties
          bin/test test/engine/commands_test.rb

